# Mood-based Song Suggester

AVALIABLE_MOODS = ["Happy", "Sad", "Love", "Relaxed", "Angry"]

SONG_LIST = [
    {"'Happy' by Pharrell Williams": "Happy"},
{"'Someone Like You' by Adele" : "Sad"},
{"'Thinking Out Loud' by Ed Sheeran" : "Love"},
{"'Weightless' by Marconi Union" : "Relaxed"},
{"'Break Stuff' by Limp Bizkit" : "Angry"},
{"'Don't Stop Me Now' by Queen" : "Happy"},
{"'Hurt' by Johnny Cash" : "Sad"},
{"'Perfect' by Ed Sheeran" : "Love"},
{"'Banana Pancakes' by Jack Johnson" : "Relaxed"},
{"'Killing in the Name' by Rage Against the Machine" : "Angry"},
{"'Walking on Sunshine' by Katrina and the Waves" : "Happy"},
{"'The Night We Met' by Lord Huron" : "Sad"},
{"'All of Me' by John Legend" : "Love"},
{"'Three Little Birds' by Bob Marley" : "Relaxed"},
{"'Enter Sandman' by Metallica" : "Angry"},
{"'Good Vibrations' by The Beach Boys" : "Happy"},
{"'Mad World' by Gary Jules" : "Sad"},
{"'At Last' by Etta James" : "Love"},
{"'Ocean Eyes' by Billie Eilish" : ("Relaxed", "Sad")},
{"'Bodies' by Drowning Pool" : "Angry"},
{"'I Wanna Dance with Somebody' by Whitney Houston" : "Happy"},
{"'Everybody Hurts' by R.E.M." : "Sad"},
{"'Can't Help Falling in Love' by Elvis Presley" : "Love"},
{"'Come Away with Me' by Norah Jones" : "Relaxed"},
{"'Given Up' by Linkin Park" : "Angry"},
{"'Lovely Day' by Bill Withers" : "Happy"},
{"'Tears in Heaven' by Eric Clapton" : "Sad"},
{"'Make You Feel My Love' by Adele" : "Love"},
{"'Breathe Me' by Sia" :("Sad", "Relaxed")},
{"'Chop Suey!' by System of a Down" : "Angry"},
{"'Mr. Blue Sky' by Electric Light Orchestra" : "Happy"},
{"'Black' by Pearl Jam" : "Sad"},
{"'Your Song' by Elton John" : "Love"},
{"'Bloom' by The Paper Kites" : "Relaxed"},
{"'Last Resort' by Papa Roach" : ("Angry", "Sad")},
{"'Here Comes the Sun' by The Beatles" : "Happy"},
{"'Skinny Love' by Bon Iver" : ("Sad", "Love")},
{"'Unchained Melody' by The Righteous Brothers" : "Love"},
{"'Holocene' by Bon Iver" : "Relaxed"},
{"'You Oughta Know' by Alanis Morissette" : "Angry"},
]

